import React from 'react'

const biblio_zona = () => {
    return (
        <div>
            <div className="image-section">
                <img className="exhibition-image" src={'https://lorraineshemeshsiteimgs.s3.us-east-2.amazonaws.com/paint-sbu/tsbu21.jpg'} alt="exhibition"/>
            </div>
            <div className="individual-words-paragraph-container">
                <h4 className="individual-words-title"><b>LORRAINE SHEMESH: BODY, LIGHT, SPACE</b></h4>
                <h4 className="individual-words-paragraph">Knowing and loving the work of Lorraine Shemesh as I do, it is hard for me to believe that her earliest desire was to become a dancer. But one can also understand that her brilliance as a figurative painter just may have its roots in the art of dance. As Martha Graham and her disciples have revealed, the human form as an abstraction, both still and in motion, may be nature's greatest visual achievement. I first became aware of Shemesh's work several years back when her focus was the human form as seen through the magical prism of water. The works were both powerful and sensitive, energy rich and calm.</h4>
                <h4 className="individual-words-paragraph">In her exploration of water on light, the play of refraction on color—the turquoise of the water on the textiles (bathing suits) of the moving body—she creates surfaces that open to deep seeing, just as water is surface opening to underwater. She's a realist who brings solidity of form to the brink of abstraction as she creates light—scintillating and accreting—modeling the body through the refraction of water, in what strikes me as furthering mode of luminist expression.</h4>
                <h4 className="individual-words-paragraph">The paintings in her new "The Space Between Us," series are an organic evolution of her work, and evolve from her "Intersections" series (2009) in which she made dramatic, life size paintings of two dancers in a unique modality of motion and stillness. Shemesh has noted that her love and ever deepening interest in dance has evolved from her experience dancing as a child. In her vision of those dancers in their black and white unitards, she creates dialectical gestures of bodies in motion that are intimate, sometimes suggesting the erotic—at once tucked in to each other, almost uroborically—while they maintain their formal dance poses and muscular realism.</h4>
                <h4 className="individual-words-paragraph">In her new paintings, she pushes further her explorations of the body in motion. She brings into a unique balance the powerful force of the dancers in their arresting white unitards—terra cotta or turquoise light often shading and striping them—with the conceptual realities of pattern and design embedded in their movements and inscribed in their dance with each other. In the black and yellow camouflage-like pattern in two of the paintings,"Puzzle," and "Inseparable," the dancers almost disappear into each other as they join in a swirling form in which they blur the limits of self and intimacy. In all of these paintings Shemesh engages us in seeing the world in formal ways—that order our perception while absorbing us in the power and beauty of the dancers and their art and human encounter.</h4>
                <h4 className="individual-words-paragraph">As always, her sensuous brush—creates both parameters and expansiveness as the pair of dancers exists both in motion and in a tableaux-like sense of arrested motion in their moments of touching. In the texture of her illusion, the plasticity of her material, she creates a way of feeling and seeing that pulls us into spaces of intimacy and a fresh view of the human body. The paintings create a balance of palpable realism and conceptual abstraction as pattern and form embody the muscular anatomy vibrant under the unitards. The patterns of colored light—terra cotta, turquoise, black and white—play with the interlocking bodies, their heads, arms, torsos, legs, feet that are engaged, almost fused with each other—as if the two verge toward one but never let go of their distinctive bodies. Striations of muscle showing through the unitards enhance the dialectical pressure between intimacy and formality. The force of these figures in motion and stasis allows us to gaze with pleasure and to meditate more deeply on the relationship between the body, light, space, and intimacy.</h4>
                <h4 className="individual-words-paragraph">The whole series brings us to some deeper insights about our humanity. The bold dramas of these selves seeking each other in the dance recall for me the final line of Theodore Roethke's final poem "Once More the Round": "we dance on, we dance on, we dance on." Whether we do as a human species—remains to be seen—but Shemesh's vision affirms life as a complex dance—a human and humane encounter with the other in which there is both mystery and the sensuous presence of the other.</h4>
                <h4 className="individual-words-paragraph">The paintings are accompanied by ten ceramic works. Shemesh writes that "My goal has been to create a dialogue between dance, paint, and clay," and these stunning pieces certainly do that. Her bowls, vessels, and hives are elegant, inventive and beautiful. Their shapes evoke archetypal forms, some of them are sensuously earthy and elemental and others exquisitely mannered. Using a Japanese neriage technique, she twines two clays of contrasting color—to patterns of slightly irregular horizontal stripes or meandering black or brown and white patches. These coils and weaves made out of the two toned clay—embody an aesthetic of the layered rock formations of the earth that Shemesh sees as emanations of "the earth's memory." These ten ceramic pieces create a rich dialogue across genres—about form and space and materials. A dialogue that engages us in the imagination's craving for beauty and order and our understanding of how we know what we know.</h4>
                <div className="individual-words-text-container">
                    <p className="individual-words-closing-text">Peter Balakian</p>
                    <p className="individual-words-closing-text">Donald M. and Constance H. Rebar Professor of Humanities, Colgate University</p>
                    <p className="individual-words-closing-text">Pulitzer Prize for Poetry 2016</p>
                </div>
            </div>
        </div>
    )
}

export default biblio_zona;