import React from 'react'

const biblio_kennedy = () => {
    return (
        <div>
            <div className="image-section">
                <img className="exhibition-image" src={'https://lorraineshemeshsiteimgs.s3.us-east-2.amazonaws.com/email_061004_B1_essay-kennedy-words.jpg'} alt="Lorraine Shemesh painting Amoeba"/>
            </div>
            <div className="individual-words-paragraph-container">
                <h4 className="individual-words-title"><b>SEEING THE EXTRAORDINARY IN THE ORDINARY</b></h4>
                <h4 className="individual-words-paragraph">An acrobatic man and woman wheel and twist in a swimming pool. Seen from below as the pair glide gracefully, his bathing trunks spark a reflected riot of dancing colors on the surface above and the light hitting the rippling water throws a bright, fluid net of criss-crossing lines on her legs.</h4>
                <h4 className="individual-words-paragraph">On display this spring at the Butler Institute of American Art in Youngstown, Ohio, Lorraine Shemesh’s figurative paintings are “brilliantly conceived and executed works that present the human form in water, with its ability to magnify and bend light,” museum director Louis Zona writes in the exhibition catalogue.</h4>
                <h4 className="individual-words-paragraph">How does Shemesh convey such motion and vivid color in her work? “I have always been interested in movement in space,” she says, “and most of the models I work with are professional dancers. Their physical flexibility is one of the contributing factors to the feeling of movement in my work. The other is imagined gesture and pushing and pulling forms around in a way that accentuates the fleeting action. The successful use of color is about making relationships work. Direct observation, intuition, and trial and error certainly have a hand in the finished work.”</h4>
                <h4 className="individual-words-paragraph">Each painting is the culmination of a long process that includes many preliminary sketches and drawings from life. “The models for the painted pool series are shown drawings of poses I’m considering developing,” Shemesh says. “I work with the figures in the studio before taking them into the water. The photo work that is done in the water is used to reference the color shifts that occur above and below the water line.” Eventually, “a lot of what the viewer sees on the canvas is imagined, made up, and renegotiated in the course of doing the painting.”</h4>
                <h4 className="individual-words-paragraph">Viewed from a distance, her paintings are “classical, figurative compositions,” notes Allan Stone in the preface to an earlier Shemesh exhibition at the Allan Stone Gallery in New York. “However, when one investigates Shemesh’s paintings up close, one discovers an extraordinary network of abstract compositions.... The pool and the swimmer become the perfect vehicle for all aspects of abstract painting because of the distortion possibilities. This in turn introduces a mysterious element into the painting because the figure dissolves magically into the depth of the pool.” All this while creating the incredibly life-like impression of athletes in action.</h4>
                <h4 className="individual-words-paragraph">In addition to figures in water, she has painted still, Hopper-esque cityscapes, and subjects as varied as elevators, fish markets, and piles of common objects like bowling shoes. Looking for the extraordinary in the ordinary, Shemesh finds even a bathroom interior to be rich with color and reflective possibilities. She also works in fiber, fabric, and clay.</h4>
                <h4 className="individual-words-paragraph">Besides the Butler Institute and the Stone Gallery, Shemesh has had solo exhibitions at the Alpha Gallery in Boston and the Rhode Island School of Design, and she has been part of group exhibitions at the National Academy Museum in New York, the Frye Art Museum in Seattle, the San Francisco Museum of Modern Art, the Musée de Carouge in Switzerland, and many others across the United States and Europe.</h4>
                <h4 className="individual-words-paragraph">She’s won a number of awards, among them Boston University’s Distinguished Alumni Award in 1992.“ A moment of appreciation like that is always a special one,” she recalls.“ I am certainly grateful to have been singled out in that way by an institution that had such a positive impact on my professional life.”</h4>
                <h4 className="individual-words-paragraph">Friendships she made at BU have been among her “most enduring and satisfying,” she says. “The fact that the professional art, music, and theatre programs at the university were housed in the same building was a source of cross-pollination and deep camaraderie.”</h4>
                <h4 className="individual-words-paragraph">“I was also lucky enough,” she adds, “to encounter an extraordinary group of working artists on the faculty, who were also generous teachers. Reed Kay, Sigmund Abeles, and John Wilson in drawing, Nick Edmunds in sculpture, and Robert Benson, Sid Hurwitz, and Joseph Ablow in design were, and remain, extremely important to me.” Painters, especially Richard Yarde and the late David Ratner,“ stand out in my mind for, by example, lighting the road along the way.”</h4>
                <h4 className="individual-words-paragraph">Furthermore, says Shemesh, who lists Vermeer, Soutine, Matisse, de Kooning, Balthus, and Morandi as some of her favorite painters, she benefited from BU’s surroundings and proximity to resources such as the Museum of Fine Arts and the Isabella Stewart Gardner Museum. “The years I spent in Boston opened my eyes to the possibilities the visual world offered. The city itself generated a sense of curiosity and wonder.”</h4>
                <div className="individual-words-text-container">
                    <p className="individual-words-closing-text">Kennedy, Patrick, "Seeing the Extraordinary in the Ordinary."</p>
                    <p className="individual-words-closing-text">Esprit. Boston University Press. (Summer 2006): illus., 4-5.</p>
                </div>
            </div>
        </div>
    )
}

export default biblio_kennedy
;